site_name: 全民瘋AI系列 [深度學習與神經網路]
site_author: 10程式中
# site_url: 
extra_css:
  - 'stylesheets/extra.css'
extra_javascript:
  - javascripts/extra.js
theme:
  name: material
  language: 'zh-TW'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  palette:
    primary: 'red'
    accent: 'red'
repo_url: https://github.com/andy6804tw/2023-15th-ironman
# use_directory_urls: false
edit_uri: ""
# Copyright
copyright: 'Copyright © 2023 - 2024 10程式中'
nav:
  - '1.基礎概念':
    - '1.1迴歸分析.md'
    - '1.2探索誤差的來源.md'
    - '1.3梯度下降的原理.md'
    - '1.4分類問題.md'
    - '1.5邏輯迴歸.md'

  - '2.神經網路概念':
    - '2.1深度學習簡介.md'
    



markdown_extensions:
  - admonition
  - footnotes
  - codehilite:
      guess_lang: false
  - toc:
      permalink: false
# plugins:
#   - search
#   - mkpdfs:
#       design: design/report.css
#       author: Tsai Yi Lin
#       # company: "10程式中"
#       toc_title: Table of contents
#       output_path: pdf/全民瘋AI系列_深度學習與神經網路_v1.1.pdf
